### ISSUE TITLE
concurrent access on brain sqlite db

### ISSUE THREAD

**Issue by ch0k0bn** [quarkslab/irma-brain#12]
when large number of probes are connected, concurrent access leads to an error in result_app.
Seen in /var/log/supervisor/results_app.log:IrmaDatabaseResultNotFound: 

[2015-01-13 13:53:41,312: ERROR/MainProcess] Task brain.tasks.job_success[85b16c15-60a8-4586-8860-185899c91
fbd] raised unexpected: IrmaDatabaseResultNotFound("The given id (63) doesn't exist in irma_job",)
IrmaDatabaseResultNotFound: The given id (63) doesn't exist in irma_job

**Comment by guillaumededrie** [comment]
Hi @ch0k0bn,
Is the issue still open?

Regards,

**Comment by ch0k0bn** [comment]
sorry this is closed in 1.2.1
